//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tweekipedia.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tweekipedia.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The url has been copied to your clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string copy_done {
            get {
                return ResourceManager.GetString("copy_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweekipedia is the service that you can tweet stylishly a Wikipedia article. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,  Input the Wikipedia URL that you share. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string firstMsg {
            get {
                return ResourceManager.GetString("firstMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The url is invalid. This service only support a Wikipedia article like https://**.wikipedia.org/wiki/ARTICLE_TITLE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string input_error {
            get {
                return ResourceManager.GetString("input_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2, Push the Tweet button, or copy the generated following URL. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string secondMsg {
            get {
                return ResourceManager.GetString("secondMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tweet {
            get {
                return ResourceManager.GetString("tweet", resourceCulture);
            }
        }
    }
}
